FROM transfusion/deployapp-base-container:ol9-java17-23.0.0-dev-app-info-2.8.3 as builder

WORKDIR /app/

COPY gradlew build.gradle.kts settings.gradle.kts ./
COPY gradle ./gradle
# COPY .gradle ./.gradle
RUN ls -lah
RUN ./gradlew dependencies

FROM transfusion/deployapp-base-container:ol9-java17-23.0.0-dev-app-info-2.8.3
COPY --from=builder /root/.gradle /root/.gradle
WORKDIR /app
COPY . /app

# RUN ls -lah
# https://stackoverflow.com/questions/29427020/how-to-run-gradle-test-when-all-tests-are-up-to-date
# "--no-build-cache", 
CMD ["./gradlew", "--no-daemon",  ":test", "--tests", "io.github.transfusion.deployapp.storagemanagementservice.external_integration.*", "--stacktrace"]