name: ci

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/graalvm/graalvm-ce:ol8-java11-22.3.0
    steps:
      - name: Install Git
        run: |
          microdnf install git -y
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      -
        name: Run unit tests
        run: |
          chmod +x run_unit_tests.sh
          ./run_unit_tests.sh
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_PAT: ${{ secrets.GITHUB_TOKEN }}
